import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname } from 'node:path'

import { PACKAGE_NAME } from '../const'

import type { RouteInput } from './definition'
import { getRoutePath, hasPrivateSegment } from './path'

export interface InlineInfoTypeDefinition {
  [key: string]: string | InlineInfoTypeDefinition
}

export type InfoTypeDefinition =
  | InlineInfoTypeDefinition
  | {
      type: 'import'
      from: string
      name: string
    }

function getRouteInputPath(file: RouteInput): string {
  return typeof file === 'string' ? file : file.routeId
}

function isPrivateRouteInput(file: RouteInput): boolean {
  if (typeof file === 'string') {
    return false
  }

  return hasPrivateSegment(file.routePath)
}

function quoteRouteKey(value: string): string {
  return `'${value.replaceAll('\\', '\\\\').replaceAll("'", "\\'")}'`
}

function quoteTypeProperty(value: string): string {
  return /^[A-Za-z_$][\w$]*$/.test(value) ? value : quoteRouteKey(value)
}

export function parseParams(files: RouteInput[], routeRoot = 'src/pages'): string[] {
  const params: string[] = []

  for (const key of files) {
    if (isPrivateRouteInput(key)) {
      continue
    }

    const path = getRoutePath(getRouteInputPath(key), routeRoot)
    if (path && path !== '/404') {
      const param = path.split('/').filter((segment) => segment.startsWith(':'))

      if (param.length || path.includes('*')) {
        const dynamic = param.map((segment) => {
          const optional = segment.endsWith('?')
          const name = segment.slice(1, optional ? -1 : undefined)
          return `${quoteTypeProperty(`$${name}`)}${optional ? '?' : ''}: string`
        })
        const splat = path.includes('*')
          ? [`${quoteTypeProperty('*')}${path.includes('*?') ? '?' : ''}: string`]
          : []
        params.push(`${quoteRouteKey(path)}: { ${[...dynamic, ...splat].join('; ')} }`)
      } else {
        params.push(`${quoteRouteKey(path)}: never`)
      }
    }
  }
  return params
}

function generateInlineType(
  obj: InlineInfoTypeDefinition,
  interfaceName: string,
  indentLevel: number = 0,
): string {
  const indent = '  '.repeat(indentLevel)
  let result = `${indent}interface ${interfaceName} {\n`

  for (const [key, value] of Object.entries(obj)) {
    const innerIndent = '  '.repeat(indentLevel + 1)
    if (typeof value === 'string') {
      result += `${innerIndent}${quoteTypeProperty(key)}: ${value}\n`
    } else if (typeof value === 'object' && value !== null) {
      const inlineType = generateInlineObjectType(value, indentLevel + 1)
      result += `${innerIndent}${quoteTypeProperty(key)}: ${inlineType}\n`
    } else {
      throw new Error(`Unsupported type descriptor for key "${key}": ${typeof value}`)
    }
  }

  result += `${indent}}`
  return result
}

function generateInlineObjectType(obj: InlineInfoTypeDefinition, indentLevel: number = 0): string {
  const indent = '  '.repeat(indentLevel)
  const innerIndent = '  '.repeat(indentLevel + 1)

  let content = ''
  for (const [key, value] of Object.entries(obj)) {
    if (typeof value === 'string') {
      content += `\n${innerIndent}${quoteTypeProperty(key)}: ${value};`
    } else if (typeof value === 'object' && value !== null) {
      const nestedType = generateInlineObjectType(value, indentLevel + 1)
      content += `\n${innerIndent}${quoteTypeProperty(key)}: ${nestedType}`
    } else {
      throw new Error(`Unsupported nested type descriptor for key "${key}"`)
    }
  }
  return `{${content}\n${indent}}`
}
export function generateRouteTypes(
  files: RouteInput[],
  output: string,
  infoDts?: InfoTypeDefinition,
  routeRoot = 'src/pages',
): number {
  const params: string[] = parseParams(files, routeRoot).sort()
  params.push(`${quoteRouteKey('/404')}: never`)

  const infoImport =
    infoDts?.type === 'import'
      ? `import type { ${infoDts.name} as FileRouteInfoDefinition } from '${infoDts.from}'\n`
      : ''
  const infoDeclaration =
    infoDts?.type === 'import'
      ? '\n  interface FileRouteInfo extends FileRouteInfoDefinition {}'
      : infoDts
        ? `\n${generateInlineType(infoDts, 'FileRouteInfo', 1)}`
        : ''

  const routeInfo = `// Auto generated by solid-file-router
/* prettier-ignore */
/* eslint-disable */
/* oxfmt-ignore */
/* oxlint-disable */

${infoImport}
import type { AnchorProps, NavigateOptions, RouterResponseInit, CustomResponse } from '@solidjs/router'

declare module '${PACKAGE_NAME}' {
  interface FileRoutePath {
    ${params.join('\n    ')}
  }${infoDeclaration}
}

declare module '@solidjs/router' {
  type Paths =
    | ${params.map((s) => s.slice(0, s.indexOf(': '))).join('\n    | ')}

  export function A(props: Omit<AnchorProps, 'href'> & { href: Paths }): JSX.Element
  export interface Navigator {
    (to: Paths, options?: Partial<NavigateOptions>): void;
    (delta: number): void;
  }
  export function redirect(url: Paths, init?: number | RouterResponseInit): CustomResponse<never>
}
`

  const previous = existsSync(output) ? readFileSync(output, 'utf8') : undefined
  if (previous !== routeInfo) {
    mkdirSync(dirname(output), { recursive: true })
    writeFileSync(output, routeInfo)
  }
  return params.length
}
