// Auto generated by solid-file-router
/* eslint-disable */

export {}

declare module 'solid-file-router' {
  namespace FileRouteInfo {
    interface Path {
      '/': never
      '/data': never
      '/nest': never
      '/nest/:id': { $id: string }
      '/nest/value': never
    }
  }
}
