// Auto generated by solid-file-router
/* eslint-disable */
declare module 'solid-file-router' {
  export interface RoutePath {
    '/': never
    '/data': never
    '/nest': never
    '/nest/:id': { id: string }
    '/nest/value': never
  }
}
