import { writeFileSync } from 'node:fs'

import { PACKAGE_NAME } from '../const'

import { patterns } from './definition'

export interface InfoTypeDefinition {
  [key: string]: string | InfoTypeDefinition
}

export function parseParams(files: string[]) {
  const filtered = files.filter((key) => !key.includes('/_') && !key.includes('/404'))
  const params: string[] = []

  for (const key of filtered) {
    const path = key
      .replace(...patterns.route)
      .replace(...patterns.splat)
      .replace(...patterns.param)
      .replace(/\([\w-]+\)\/|\/?_layout/g, '')
      .replace(/\/?index|\./g, '/')
      .replace(/(\w)\/$/g, '$1')
      .split('/')
      .map((segment) => segment.replace(...patterns.optional))
      .join('/')

    if (path) {
      const param = path.split('/').filter((segment) => segment.startsWith(':'))

      if (param.length || path.includes('*')) {
        const dynamic = param.length
          ? param.map((p) => '$' + p.replace(/:(.+)(\?)?/, '$1$2:') + ' string')
          : []
        const splat = path.includes('*') ? ["'*': string"] : []
        params.push(`'/${path}': { ${[...dynamic, ...splat].join('; ')} }`)
      } else {
        const key = path.length > 1 ? `/${path}` : path
        params.push(`'${key}': never`)
      }
    }
  }
  return params
}

function generateInlineType(
  obj: InfoTypeDefinition,
  interfaceName: string,
  indentLevel: number = 0,
): string {
  const indent = '  '.repeat(indentLevel)
  let result = `${indent}interface ${interfaceName} {\n`

  for (const [key, value] of Object.entries(obj)) {
    const innerIndent = '  '.repeat(indentLevel + 1)
    if (typeof value === 'string') {
      result += `${innerIndent}${key}: ${value}\n`
    } else if (typeof value === 'object' && value !== null) {
      const inlineType = generateInlineObjectType(value, indentLevel + 1)
      result += `${innerIndent}${key}: ${inlineType}\n`
    } else {
      throw new Error(`Unsupported type descriptor for key "${key}": ${typeof value}`)
    }
  }

  result += `${indent}}`
  return result
}

function generateInlineObjectType(obj: InfoTypeDefinition, indentLevel: number = 0): string {
  const indent = '  '.repeat(indentLevel)
  const innerIndent = '  '.repeat(indentLevel + 1)

  let content = ''
  for (const [key, value] of Object.entries(obj)) {
    if (typeof value === 'string') {
      content += `\n${innerIndent}${key}: ${value};`
    } else if (typeof value === 'object' && value !== null) {
      const nestedType = generateInlineObjectType(value, indentLevel + 1)
      content += `\n${innerIndent}${key}: ${nestedType}`
    } else {
      throw new Error(`Unsupported nested type descriptor for key "${key}"`)
    }
  }
  return `{${content}\n${indent}}`
}
let cache = ''

export function generateRouteTypes(
  files: string[],
  output: string,
  infoDts?: InfoTypeDefinition,
): number {
  const params: string[] = parseParams(files).sort()
  params.push("'/404': never")

  const routeInfo = `// Auto generated by solid-file-router
/* prettier-ignore */
/* eslint-disable */
/* oxfmt-ignore */
/* oxlint-disable */

export {}

declare module '${PACKAGE_NAME}' {
  interface FileRoutePath {
    ${params.join('\n    ')}
  }${infoDts ? '\n' + generateInlineType(infoDts, 'FileRouteInfo', 1) : ''}
}

declare module '@solidjs/router' {
  import type { AnchorProps, NavigateOptions, RouterResponseInit, CustomResponse } from '@solidjs/router'

  type Paths =
    | ${params.map((s) => s.split(': ')[0]).join('\n    | ')}

  export declare function A(props: Omit<AnchorProps, 'href'> & { href: Paths }): JSX.Element
  export interface Navigator {
    (to: Paths, options?: Partial<NavigateOptions>): void;
    (delta: number): void;
  }
  export declare function redirect(url: Paths, init?: number | RouterResponseInit): CustomResponse<never>
}
`

  if (cache !== routeInfo) {
    cache = routeInfo
    writeFileSync(output, routeInfo)
  }
  return params.length
}
