import { writeFileSync } from 'node:fs'
import { PACKAGE_NAME } from '../const'
import { patterns } from './definition'

export interface InfoTypeDefinition {
  [key: string]: string | InfoTypeDefinition
}

export function parseParams(files: string[]) {
  const filtered = files.filter(
    (key) => !key.includes('/_') && !key.includes('/404'),
  )
  const params: string[] = []

  for (const key of filtered) {
    const path = key
      .replace(...patterns.route)
      .replace(...patterns.splat)
      .replace(...patterns.param)
      .replace(/\([\w-]+\)\/|\/?_layout/g, '')
      .replace(/\/?index|\./g, '/')
      .replace(/(\w)\/$/g, '$1')
      .split('/')
      .map((segment) => segment.replace(...patterns.optional))
      .join('/')

    if (path) {
      const param = path.split('/').filter((segment) => segment.startsWith(':'))

      if (param.length || path.includes('*')) {
        const dynamic = param.length
          ? param.map((p) => '$' + p.replace(/:(.+)(\?)?/, '$1$2:') + ' string')
          : []
        const splat = path.includes('*') ? ["'*': string"] : []
        params.push(`'/${path}': { ${[...dynamic, ...splat].join('; ')} }`)
      } else {
        const key = path.length > 1 ? `/${path}` : path
        params.push(`'${key}': never`)
      }
    }
  }
  return params
}

function parseInfoDef(def: InfoTypeDefinition) {
  return JSON.stringify(
    { ...def, '[x: string]': 'unknown' },
    (_, v) => (typeof v === 'string' ? `$${v}$` : v),
    2,
  )
    .replace(/"\$([^$]+)\$"/g, '$1')
    .replace(/\n/g, '\n    ')
    .replace('"[x: string]"', '[x: string]')
}

let cache = ''

export function generateRouteTypes(
  files: string[],
  output: string,
  infoDts?: InfoTypeDefinition,
): number {
  const params: string[] = parseParams(files)

  const routeInfo = `// Auto generated by solid-file-router
/* eslint-disable */

export {}

declare module '${PACKAGE_NAME}' {
  namespace FileRouteInfo {
    interface Path {
      ${params.sort().join('\n      ')}
    }
    interface Info ${infoDts ? parseInfoDef(infoDts) : '{}'}
  }
}
`

  if (cache !== routeInfo) {
    cache = routeInfo
    writeFileSync(output, routeInfo)
  }
  return params.length
}
